services:
  api-local:
    build: ../api
    container_name: scales-api-local
    restart: unless-stopped
    volumes:
      - ./settings.toml:/app/settings.toml
    ports:
      - "8080:8000"
    profiles: [local]
#    devices:
#      - "/dev/ttyUSB0:/dev/ttyUSB0"
#    env_file:
#      - .env


  api-dockerhub:
    image: kraleksey/scales_api_async:latest
    container_name: scales-api
    restart: unless-stopped
    volumes:
      - ./settings.toml:/app/settings.toml
    ports:
      - "8080:8000"
    profiles: [dockerhub]
#    env_file:
#      - .env
#    devices:
#      - "/dev/ttyUSB0:/dev/ttyUSB0"
