services:
  api-local:
    build: ../api
    container_name: scales-api
    restart: unless-stopped
    volumes:
      - ./settings.toml:/app/settings.toml
    ports:
      - 8100:8000
    profiles:
      - local
#    devices:
#      - "/dev/ttyUSB0:/dev/ttyUSB0"
#    env_file:
#      - .env


  api-dockerhub:
    image: kraleksey/owen_counter_api:latest
    restart: unless-stopped
    profiles:
      - dockerhub
#    devices:
#      - "/dev/ttyUSB0:/dev/ttyUSB0"

