name: ScalesAPIAsync workflow
on:
  push:
    branches:
      - 'master'
jobs:
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: 'master'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: api
          push: true
          tags: kraleksey/scales_api_async:latest

  send_message:
    if: ${{ always() }}
    needs: [ build_and_push_to_docker_hub ]
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }}
            Actor: ${{ github.actor }}
            Branch: ${{ github.ref_name }}
            Results:
              building and pushing back: ${{ needs.build_and_push_to_docker_hub.result }}
